# Generated by Django 2.0 on 2017-12-08 04:40

from django.db import migrations, models
from domio.settings import BASE_DIR
import csv


def forwards(apps, schema):
    Zipcode = apps.get_model('zipcode', 'Zipcode')
    zipcodes = []
    with open(BASE_DIR + '/domio/fixtures/zipcodes.csv') as zips:
        reader = csv.reader(zips)
        for row in reader:
            zip_len = len(row[0])
            zipcode = row[0]
            if zip_len < 5:
                zipcode = ("0" * (5 - zip_len)) + zipcode

            zipcode = Zipcode(zipcode=zipcode, query_count=0)
            zipcodes.append(zipcode)

    Zipcode.objects.using(schema.connection.alias).bulk_create(zipcodes)


def backwards(apps, schema):
    Zipcode = apps.get_model('zipcode', 'Zipcode')
    Zipcode.objects.using(schema.connection.alias).all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=5)),
                ('query_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.RunPython(forwards, backwards)
    ]
